### ISSUE TITLE
License information for including into the Sming project 

### ISSUE THREAD

**Issue by ADiea** [theGanymedes/si4432#2]
Hi, I have modified your code for use with the ESP8266 device and want to integrate it to the Sming open source framework here: https://github.com/anakod/Sming/pull/215

The license is not very clear from the source code. Please let me know what kind of license you want to distribute your code: MIT, GPL, LGPL etc

**Comment by theGanymedes** [comment]
MIT is good enough for me;  feel free to fo anything ad long as you give credit ;)

**Comment by ADiea** [comment]
Nice to hear, thanks again for your work!

**Comment by theGanymedes** [comment]
I'm glad that it helped you :)
